const fs = require('fs');
const assert = require('node:assert/strict');
const {initializeTestEnvironment, assertFails, assertSucceeds} = require('@firebase/rules-unit-testing');
const {SecureStore} = require('../assets/secure-store');
const C = require('../assets/control-core');
let environment;
async function main() {
  environment = await initializeTestEnvironment({projectId:'demo-stock-control',database:{host:'127.0.0.1',port:9000,rules:fs.readFileSync('database.rules.json','utf8')}});
  const profile = (uid,role,company_id='A',op='ITC-B01') => ({uid,email:uid+'@example.test',user_id:uid,role,company_id,is_active:true,controlScopes:{[op]:true},controlScopeKeys:{[company_id+'|'+op]:true}});
  const profiles = Object.fromEntries([profile('controller','Contrôleur'),profile('second','Contrôleur'),profile('manager','Gestionnaire'),profile('supervisor','Superviseur'),profile('other','Contrôleur','B'),profile('noScope','Contrôleur','A','MOOV')].map(p => [p.uid,p]));
  delete profiles.noScope.controlScopes;
  delete profiles.noScope.controlScopeKeys;
  await environment.withSecurityRulesDisabled(async c => c.database().ref().set({auth_profiles:profiles,tenant_branding:{A:{status:'active'},B:{status:'active'}},itc_data:{users:Object.fromEntries(Object.entries(profiles).map(([k,p]) => [k,{...p,id:k,name:k}])),stock:{a:{company_id:'A',op:'ITC-B01',scope_key:'A|ITC-B01',label:'Câble',qty:100},b:{company_id:'A',op:'ITC-B02',scope_key:'A|ITC-B02',label:'Autre stock',qty:20},foreign:{company_id:'B',op:'ITC-B01',scope_key:'B|ITC-B01',label:'Autre entreprise',qty:40}}}}));
  const client = uid => environment.authenticatedContext(uid).database();
  const controller = client('controller'), manager = client('manager'), supervisor = client('supervisor');
  const base = 'stock_control/A/ITC-B01';
  const inv = db => db.ref(base+'/inventories/i');
  const stock = db => db.ref('itc_data/stock/a');
  await assertSucceeds(controller.ref('itc_data/stock').orderByChild('scope_key').equalTo('A|ITC-B01').once('value'));
  await assertSucceeds(controller.ref('itc_data/stock').orderByChild('company_id').equalTo('A').once('value'));
  await assertSucceeds(controller.ref('itc_data/stock').orderByChild('scope_key').equalTo('A|ITC-B02').once('value'));
  await assertSucceeds(controller.ref('itc_data/stock/b').once('value'));
  await assertSucceeds(client('noScope').ref('itc_data/stock/b').once('value'));
  await assertFails(controller.ref('itc_data/stock').orderByChild('company_id').equalTo('B').once('value'));
  await assertFails(controller.ref('itc_data/stock').orderByChild('scope_key').equalTo('B|ITC-B01').once('value'));
  await assertFails(controller.ref('itc_data/stock/foreign').once('value'));
  await assertFails(stock(controller).child('qty').set(99));
  await assertFails(controller.ref('auth_profiles/controller/controlScopes/ITC-B02').set(true));
  const store = new SecureStore(controller,()=>{},e=>{throw e;});
  await store.connect({uid:'controller'});
  assert.deepEqual(store.value().stock.map(s=>s._dbKey).sort(),['a','b']);
  await assert.rejects(store.save(store.value()),/module Contrôle/); store.stop();
  const dossier = {title:'Inventaire contradictoire',status:'draft',createdBy:'controller',createdAt:'2026-09-15T08:00:00Z'};
  await assertSucceeds(inv(controller).set(dossier));
  await assertFails(inv(client('other')).once('value'));
  await assertSucceeds(inv(client('noScope')).once('value'));
  await assertSucceeds(controller.ref('stock_control/A/ITC-B02/missions/m').set({title:'Contrôle B02',status:'open',createdBy:'controller',createdAt:'2026-09-15'}));
  await assertFails(manager.ref('stock_control/A/ITC-B02/missions/m').once('value'));
  await assertFails(controller.ref('stock_control/B/ITC-B02/missions/m').set({title:'Autre entreprise',status:'open',createdBy:'controller',createdAt:'2026-09-15'}));
  await assertSucceeds(controller.ref(base+'/lock').set('i'));
  await assertFails(manager.ref('itc_data/stock/a/qty').set(90));
  await assertFails(stock(manager).remove());
  await assertFails(manager.ref('itc_data/stock/new').set({op:'ITC-B01',company_id:'A',label:'New',qty:1}));
  await assertSucceeds(inv(controller).update({status:'counting',referenceAt:'2026-09-15T09:00:00Z',lines:{a:{label:'Câble',theoretical:100}}}));
  await assertFails(inv(client('second')).child('lines/a/counted').set(99));
  await assertSucceeds(inv(controller).child('lines/a/counted').set(98));
  await assertFails(inv(manager).child('lines/a/counted').set(100));
  await assertSucceeds(inv(manager).child('managerCounts/a').set({qty:98,by:'manager',at:'2026-09-15T09:10:00Z'}));
  await assertSucceeds(inv(manager).child('managerResponse').set({text:'Accord, deux unités manquantes.',by:'manager',at:'2026-09-15T09:11:00Z'}));
  await assertSucceeds(inv(controller).child('status').set('review'));
  await assertFails(inv(controller).child('status').set('approved'));
  await assertFails(inv(controller).child('lines/a/counted').set(97));
  await assertSucceeds(inv(supervisor).update({status:'approved',decision:{text:'Écart confirmé',by:'supervisor',at:'2026-09-15T10:00:00Z'}}));
  const inventory = (await inv(supervisor).once('value')).val();
  const before = (await stock(supervisor).once('value')).val();
  const after = C.adjustment(before,inventory,'a','i');
  assert.equal(after.qty,98);
  await C.applyAdjustment(stock(supervisor),inventory,'a','i');
  await C.applyAdjustment(stock(supervisor),inventory,'a','i');
  assert.equal((await stock(supervisor).once('value')).val().qty,98);
  assert.deepEqual(C.adjustment(after,inventory,'a','i'),after);
  await assertFails(stock(supervisor).set({...after,qty:96}));
  await assertSucceeds(inv(supervisor).child('status').set('closed'));
  await assertFails(inv(controller).child('lines/a/counted').set(0));
  await assertSucceeds(supervisor.ref(base+'/lock').remove());
  await assertFails(stock(manager).child('controlAdjustments/i').remove());
  await assertSucceeds(stock(manager).child('qty').set(99));
  const managerStore = new SecureStore(manager,()=>{},e=>{throw e;});
  await managerStore.connect({uid:'manager'});
  const deliveryData = managerStore.value();
  deliveryData.stock.find(s=>s._dbKey === 'a').qty = 101;
  await managerStore.save(deliveryData);managerStore.stop();
  const journal=(await controller.ref('itc_data/stockMovements').orderByChild('scope_key').equalTo('A|ITC-B01').once('value')).val();
  const movement=Object.values(journal)[0];
  assert.equal(movement.before,99);assert.equal(movement.after,101);assert.equal(movement.actorUid,'manager');
  await assertFails(manager.ref('itc_data/stockMovements/'+Object.keys(journal)[0]).remove());
  const anomaly = controller.ref(base+'/anomalies/a');
  await assertSucceeds(anomaly.set({title:'Manque',status:'open',createdBy:'controller',createdAt:'2026-09-15'}));
  await assertSucceeds(manager.ref(base+'/anomalies/a/response').set({text:'Recherche effectuée',by:'manager',at:'2026-09-15'}));
  await assertSucceeds(anomaly.child('description').set('Deux unités manquantes'));
  await assertFails(anomaly.child('response/text').set('Fausse réponse'));
  const file={name:'preuve.pdf',type:'application/pdf',size:3,data:'YWJj',by:'controller',at:'2026-09-15'};
  await assertSucceeds(anomaly.child('attachments/file').set(file));
  await assertFails(anomaly.child('attachments/large').set({...file,size:300000}));
  await assertSucceeds(anomaly.update({status:'closed',description:'Recherche terminée',evidence:'Procès-verbal joint'}));
  await assertFails(anomaly.child('description').set('Modification après clôture'));
  await assertFails(anomaly.child('attachments/file/data').set('AAAA'));
  const transfer=controller.ref(base+'/checks/transfer');
  await assertSucceeds(transfer.set({title:'Transfert contrôlé',status:'open',createdBy:'controller',createdAt:'2026-09-15',source:'transfer',sentQty:10,toStock:'ITC-B02'}));
  await assertFails(transfer.update({receivedQty:9,status:'conform'}));
  await assertSucceeds(transfer.update({receivedQty:9,status:'anomaly'}));
  const audit=controller.ref(base+'/audits/audit');
  await assertSucceeds(audit.set({title:'Audit',status:'open',createdBy:'controller',createdAt:'2026-09-15'}));
  await assertFails(audit.update({status:'closed',description:'Terminé',evidence:'Vérifié'}));
  await assertSucceeds(audit.update({status:'closed',description:'Terminé',evidence:'Vérifié',checklist:Object.fromEntries(Array.from({length:8},(_,i)=>[i,{result:'Conforme',proof:'Vérification documentée'}]))}));
  await assertSucceeds(controller.ref(base+'/events/e').set({actorUid:'controller',at:'2026-09-15',message:'Contrôle réalisé'}));
  await assertFails(controller.ref(base+'/events/e/message').set('Réécriture'));
  await assertFails(controller.ref(base+'/events/e').remove());
  assert.throws(()=>C.quantity(''),/quantité/);
  assert.throws(()=>C.quantity(-1),/positif/);
  assert.throws(()=>C.adjustment({...before,qty:101},inventory,'a','i'),/modifié/);
  console.log('PASS: controller scope isolation, real transport, frozen inventory, independent counts, approval, exactly-once adjustment, immutable journal and role separation.');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(environment) await environment.cleanup();});
