const fs=require('fs'),assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const uuid=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
(async()=>{
 const db=new PGlite();
 await db.exec(`CREATE ROLE authenticated; CREATE ROLE anon; CREATE ROLE service_role; CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY); CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('test.uid',true),'')::uuid $$; GRANT USAGE ON SCHEMA auth TO authenticated;`);
 await db.exec(fs.readFileSync('supabase/migrations/202609180002_app_backend.sql','utf8').split('DO $$')[0]);
 await db.exec('GRANT SELECT,INSERT,UPDATE,DELETE ON app_records,app_settings TO authenticated; GRANT SELECT ON app_profiles TO authenticated;');
 await db.exec(fs.readFileSync('supabase/migrations/202609180003_cable_offcuts.sql','utf8').split('DO $$')[0]);
 await db.exec(fs.readFileSync('supabase/migrations/202609180005_validator_workflow.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202609190001_validator_bureaus.sql','utf8'));
 for(const [id,role,company,scopes] of [[1,'Coordinateur','A',{}],[2,'Validateur','A',{'ITC-B01':true,CIC:true,MTN:true,OCI:true}],[3,'Gestionnaire','A',{'ITC-B01':true}],[4,'Gestionnaire','A',{'ITC-B02':true,MOOV:true}],[5,'Validatrice','B',{}],[6,'Technicien','A',{}],[7,'Validateur','A',{'ITC-B02':true,MOOV:true}],[8,'Validatrice','A',{}]]){
  await db.query('INSERT INTO auth.users VALUES($1)',[uuid(id)]);
  await db.query("INSERT INTO app_profiles(user_id,company_id,role,control_scopes,profile) VALUES($1,$2,$3,$4,$5)",[uuid(id),company,role,JSON.stringify(scopes),JSON.stringify({id,name:role+' '+id})]);
 }
 await db.exec("INSERT INTO stock_workflow_config VALUES('A',true),('B',true)");
 const as=async id=>{await db.exec('RESET ROLE');await db.query("SELECT set_config('test.uid',$1,false)",[uuid(id)]);await db.exec('SET ROLE authenticated');};
 const read=async(collection,key)=>{await db.exec('RESET ROLE');return (await db.query('SELECT payload FROM app_records WHERE collection=$1 AND record_key=$2',[collection,key])).rows[0]?.payload;};
 const insert=async(collection,key,payload)=>db.query('INSERT INTO app_records(collection,record_key,company_id,payload) VALUES($1,$2,$3,$4)',[collection,key,'A',JSON.stringify(payload)]);
 await insert('stock','stock1',{op:'ITC-B01',label:'Cable',qty:100});
 const request={id:'R1',op:'ITC-B01',items:[{label:'Cable',qty:20},{label:'Cable',qty:10}],status:'EN ATTENTE GESTIONNAIRE'};
 await as(1);await insert('demandes','r1',request);
 assert.equal((await read('demandes','r1')).status,'EN ATTENTE VALIDATEUR');
 const notices=(await db.query("SELECT payload->'userId' AS recipient FROM app_records WHERE collection='notifications'")).rows;
 assert.deepEqual(notices.map(n=>n.recipient),[2],'only B01 validator notified for B01 request');
 for(const actorId of [7,8]){await as(actorId);await assert.rejects(db.query("SELECT decide_stock_request('r1',true,$1,'')",[uuid(3)]),/hors de votre bureau/);await assert.rejects(db.exec("SELECT decide_stock_request('r1',false,NULL,'Refus')"),/hors de votre bureau/);}
 await as(1);await assert.rejects(db.query("SELECT decide_stock_request('r1',true,$1,'')",[uuid(3)]),/réservée/);
 await as(5);await assert.rejects(db.query("SELECT decide_stock_request('r1',true,$1,'')",[uuid(3)]),/absent/);
 await as(3);await assert.rejects(db.query("SELECT issue_validated_request('r1','Manager','DEP')"),/affecté/);
 await assert.rejects(db.exec("UPDATE app_records SET payload=jsonb_set(payload,'{qty}','0') WHERE record_key='stock1'"),/débit/);
 await assert.rejects(insert('sorties','fake',{items:request.items}),/validé/);
 await as(2);await assert.rejects(db.query("SELECT decide_stock_request('r1',true,$1,'')",[uuid(4)]),/ne gère pas/);
 await assert.rejects(db.exec("SELECT decide_stock_request('r1',false,NULL,'')"),/Motif/);
 await db.query("SELECT decide_stock_request('r1',true,$1,'Accord')",[uuid(3)]);
 assert.equal((await read('stock','stock1')).qty,100,'approval does not debit');
 await as(2);await assert.rejects(db.query("SELECT decide_stock_request('r1',true,$1,'')",[uuid(3)]),/déjà traité/);
 await as(4);await assert.rejects(db.exec("SELECT issue_validated_request('r1','Manager','DEP')"),/autre gestionnaire/);
 await as(3);await db.exec("SELECT issue_validated_request('r1','Manager','DEP')");
 await db.exec("SELECT issue_validated_request('r1','Manager','DEP')");
 assert.equal((await read('stock','stock1')).qty,70,'duplicate requests aggregated and retry idempotent');
 assert.equal((await db.query("SELECT count(*)::int n FROM app_records WHERE collection='sorties'")).rows[0].n,1);
 await as(1);await insert('demandes','r2',{...request,id:'R2'});
 await as(2);await db.exec("SELECT decide_stock_request('r2',false,NULL,'Quantité non justifiée')");
 await as(3);await assert.rejects(db.exec("SELECT issue_validated_request('r2','Manager','DEP')"),/affecté/);
 await as(1);await insert('demandes','r3',{...request,id:'R3',items:[{label:'Cable',qty:60},{label:'Absent',qty:1}]});
 await as(2);await db.query("SELECT decide_stock_request('r3',true,$1,'')",[uuid(3)]);
 await as(3);await assert.rejects(db.exec("SELECT issue_validated_request('r3','Manager','DEP')"),/absent/);
 assert.equal((await read('stock','stock1')).qty,70,'failure rolls entire issue back');
 await as(2);await assert.rejects(db.exec("UPDATE app_records SET payload=jsonb_set(payload,'{qty}','999') WHERE record_key='stock1'"),/lecture seule/);
 await as(1);await assert.rejects(db.query('SELECT save_app_changes($1)',[JSON.stringify([{collection:'stock',record_key:'stock1',company_id:'A',payload:{op:'ITC-B01',label:'Cable',qty:100},previous:{op:'ITC-B01',label:'Cable',qty:100}}])]),/autre utilisateur/);
 await db.exec('RESET ROLE');
 assert.equal((await db.query("SELECT save_offcut_state('A','ITC-B01',NULL,'{\"lots\":{}}') saved")).rows[0].saved,true);
 assert.equal((await db.query("SELECT save_offcut_state('A','ITC-B01',NULL,'{\"lots\":{}}') saved")).rows[0].saved,false);
 await as(2);await assert.rejects(db.exec("SELECT save_offcut_state('A','ITC-B01',NULL,'{}')"),/permission/);
 await as(1);await insert('demandes','b02',{...request,id:'B02',op:'MOOV'});
 await as(2);await assert.rejects(db.exec("SELECT decide_stock_request('b02',false,NULL,'Refus')"),/hors de votre bureau/);
 await as(7);await db.query("SELECT decide_stock_request('b02',true,$1,'')",[uuid(4)]);
 await as(1);await insert('demandes','mixed',{...request,id:'MIXED',items:[{op:'ITC-B01',label:'Cable',qty:1},{op:'MOOV',label:'Cable',qty:1}]});
 for(const actorId of [2,7]){await as(actorId);await assert.rejects(db.exec("SELECT decide_stock_request('mixed',false,NULL,'Refus')"),/hors de votre bureau/);}
 await db.close();
 console.log('PASS: roles, tenant isolation, approval/refusal, dedicated manager, atomic debit, insufficient stock rollback, duplicate issue, stale save, offcut concurrency guard.');
})().catch(e=>{console.error(e);process.exitCode=1});
