const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const uuid=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
const migration=name=>fs.readFileSync('supabase/migrations/'+name,'utf8');
(async()=>{
 const db=new PGlite(),company='COMP-ITC-LEGACY';
 await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('test.uid',true),'')::uuid $$;GRANT USAGE ON SCHEMA auth TO authenticated;`);
 await db.exec(migration('202609180002_app_backend.sql').split('DO $$')[0]);
 await db.exec('GRANT SELECT,INSERT,UPDATE,DELETE ON app_records,app_settings TO authenticated;GRANT SELECT ON app_profiles TO authenticated;');
 for(const file of ['202609180005_validator_workflow.sql','202609190001_validator_bureaus.sql','202609190004_unconditional_workflow.sql','202609190005_city_stocks.sql','202609240001_repair_rejected_bon_actions.sql','202609240004_bureau02_substocks.sql','202609240005_explicit_substock_issues.sql','202609250002_bon_validity_scanner.sql','202609260001_bon_drawn_signatures.sql'])await db.exec(migration(file));
 const fixture=async(id,role,office,service,tenant=company)=>{
  const details={id,uid:uuid(id),company_id:tenant,name:'Compte '+id,role,...(office?{office}:{}),...(service?{serviceAbbreviation:service}:{})};
  await db.query('INSERT INTO auth.users VALUES($1,$2)',[uuid(id),id+'@example.test']);
  await db.query('INSERT INTO app_profiles(user_id,company_id,role,control_scopes,profile) VALUES($1,$2,$3,$4,$5)',[uuid(id),tenant,role,id===6?{MOOV:true}:{'ITC-B01':true},details]);
  await db.query("INSERT INTO app_records VALUES('users',$1,$2,$3,now())",[uuid(id),tenant,details]);
 };
 await fixture(1,'Superviseur');await fixture(2,'Technicien');await fixture(3,'Coordinateur','B02');await fixture(4,'Coordinatrice','B01','B2B');await fixture(5,'Coordinateur','B02','MAIN');await fixture(6,'Validateur','B02','MAIN');await fixture(7,'Validateur','B01','B2B');await fixture(8,'Gestionnaire','B01','B2B');await fixture(9,'Superviseur',null,null,'OTHER');await fixture(10,'Contrôleur');await fixture(11,'Technicien',null,null,'OTHER');
 const latest='202609260002_account_affiliations.sql';await db.exec(migration(latest));await db.exec(migration(latest));
 const as=async id=>{await db.exec('RESET ROLE');await db.query("SELECT set_config('test.uid',$1,false)",[uuid(id)]);await db.exec('SET ROLE authenticated');};
 const user=async id=>(await db.query("SELECT payload FROM app_records WHERE collection='users' AND record_key=$1",[uuid(id)])).rows[0].payload;
 assert.equal((await user(2)).office,'B02');assert.equal((await user(2)).serviceAbbreviation,'B2B');assert.equal((await user(11)).office,undefined);assert.equal((await user(1)).office,undefined);assert.equal((await user(10)).serviceAbbreviation,undefined);
 await as(3);assert.equal((await user(3)).canChooseInitialService,true);await db.exec("SELECT choose_initial_coordinator_service('B2B')");assert.equal((await user(3)).serviceAbbreviation,'B2B');await assert.rejects(db.exec("SELECT choose_initial_coordinator_service('MAIN')"),/responsable/);
 await as(2);await assert.rejects(db.exec("SELECT choose_initial_coordinator_service('MAIN')"),/responsable/);await assert.rejects(db.query('SELECT assign_account_affiliation($1,$2,$3)',[uuid(2),'B01','MAIN']),/responsable/);
 await assert.rejects(db.query("UPDATE app_records SET payload=payload||'{\"office\":\"B01\"}' WHERE record_key=$1",[uuid(2)]),/rattachement/);
 const create=(key,coordinator=3,extra={})=>db.query("INSERT INTO app_records(collection,record_key,company_id,payload) VALUES('demandes',$1,$2,$3)",[key,company,{id:key,company_id:company,workflow:'TECH_BON_SORTIE',technicienUid:uuid(2),coordinateurId:coordinator,status:'EN ATTENTE COORDINATION',serviceAbbreviation:'MAIN',originOffice:'B01',items:[{op:'ITC-B01',label:'CABLE',qty:1}],...extra}]);
 await assert.rejects(create('wrong-office',4),/coordinateur actif/);await assert.rejects(create('wrong-service',5),/coordinateur actif/);await create('good');
 const request=async key=>(await db.query("SELECT payload FROM app_records WHERE collection='demandes' AND record_key=$1",[key])).rows[0].payload;
 assert.equal((await request('good')).originOffice,'B02');assert.equal((await request('good')).serviceAbbreviation,'B2B');
 await assert.rejects(db.exec("UPDATE app_records SET payload=payload||'{\"originOffice\":\"B01\"}' WHERE record_key='good'"),/réaffectés/);
 await as(3);await db.exec("UPDATE app_records SET payload=payload||'{\"status\":\"EN ATTENTE VALIDATEUR\"}' WHERE record_key='good'");
 const notified=(await db.query("SELECT payload->>'userId' id FROM app_records WHERE collection='notifications'")).rows.map(r=>r.id);assert.ok(notified.includes('6'));assert.ok(!notified.includes('7'),'notifications follow origin office, not material stocks');
 await as(7);await assert.rejects(db.query('SELECT decide_stock_request($1,true,$2,\'\')',['good',uuid(8)]),/bureau/);
 await as(6);await db.query('SELECT decide_stock_request_signed($1,true,$2,\'\',\'Validateur bureau 02\',NULL)',['good',uuid(8)]);
 assert.equal((await request('good')).status,'EN ATTENTE GESTIONNAIRE','B02 validator processes B2B bon despite being MAIN and materials from B01');
 await db.exec('RESET ROLE');await db.exec("UPDATE app_records SET payload=payload||jsonb_build_object('bonValidUntil',clock_timestamp()-interval '1 second') WHERE record_key='good'");
 await as(8);await db.exec("SELECT request_bon_renewal('good')");const expired=await request('good');await as(7);await assert.rejects(db.query('SELECT confirm_bon_renewal($1,$2,true,\'Présent\')',['good',JSON.stringify(expired.bonValidUntil)]),/affectation/);await as(6);await db.query('SELECT confirm_bon_renewal($1,$2,true,\'Présent\')',['good',JSON.stringify(expired.bonValidUntil)]);assert.equal((await request('good')).bonRenewals.length,1);
 await as(9);await assert.rejects(db.query('SELECT assign_account_affiliation($1,$2,$3)',[uuid(2),'B01','MAIN']),/responsable/);
 await as(1);await assert.rejects(db.query('SELECT assign_account_affiliation($1,$2,$3)',[uuid(10),'B01','MAIN']),/rôle/);await db.query('SELECT assign_account_affiliation($1,$2,$3)',[uuid(2),'B01','DEP']);assert.equal((await user(2)).serviceAbbreviation,'DEP');assert.equal((await request('good')).originOffice,'B02','historical request origin is immutable');
 await db.exec('RESET ROLE');await db.exec(migration(latest));assert.equal((await user(2)).office,'B01','migration rerun preserves subsequent assignments');
 await db.query('INSERT INTO auth.users VALUES($1,$2)',[uuid(20),'20@example.test']);
 const register=(office,service)=>db.query('SELECT register_company_user_affiliated($1,$2,$3,\'Coordinateur\',\'Nouveau\',\'20@example.test\',ARRAY[]::text[],$4,$5)',[uuid(1),uuid(20),company,office,service]);
 await assert.rejects(register(null,null),/obligatoires/);assert.equal((await db.query('SELECT count(*)::int n FROM app_profiles WHERE user_id=$1',[uuid(20)])).rows[0].n,0,'registration rollback prevents incomplete account');await register('B02','B2B');assert.equal((await user(20)).canChooseInitialService,false);
 await as(20);await assert.rejects(db.exec("SELECT choose_initial_coordinator_service('MAIN')"),/responsable/);
 await db.exec('RESET ROLE');await db.query('INSERT INTO auth.users VALUES($1,$2)',[uuid(21),'21@example.test']);await db.query('SELECT register_company_user_affiliated($1,$2,$3,\'Technicien\',\'Nouveau\',\'21@example.test\',ARRAY[]::text[],\'B01\',\'MAIN\')',[uuid(1),uuid(21),company]);await db.exec(migration(latest));assert.equal((await user(21)).office,'B01','rerun must not migrate technicians created after initial migration');assert.equal((await user(21)).serviceAbbreviation,'MAIN');
 const context={window:{}};vm.createContext(context);vm.runInContext(fs.readFileSync('assets/account-affiliation.js','utf8'),context);const module=context.window.AccountAffiliation;
 const tech={role:'Technicien',company_id:company,office:'B02',serviceAbbreviation:'B2B'},coords=[{...tech,id:1,role:'Coordinateur'},{...tech,id:2,role:'Coordinateur',office:'B01'},{...tech,id:3,role:'Coordinatrice',serviceAbbreviation:'DEP'},{...tech,id:4,role:'Coordinateur',is_active:false},{...tech,id:5,role:'Coordinateur',company_id:'OTHER'},{...tech,id:6,role:'Superviseur Terrain'}];
 assert.equal(JSON.stringify(module.coordinators(tech,coords).map(u=>u.id)),'[1]');assert.equal(module.coordinators({...tech,office:''},coords).length,0);
 vm.runInContext(fs.readFileSync('assets/validator-workflow.js','utf8'),context);context.window.ValidatorWorkflow.setup({profile:()=>({role:'Validateur',office:'B02',serviceAbbreviation:'MAIN',controlScopes:{}})});assert.equal(context.window.ValidatorWorkflow.covers({originOffice:'B02',serviceAbbreviation:'B2B'}),true);assert.equal(context.window.ValidatorWorkflow.covers({originOffice:'B01'}),false);assert.equal(context.window.ValidatorWorkflow.covers({}),false);
 assert.match(module.ownSection({role:'Coordinateur',canChooseInitialService:true}),/Enregistrer mon service/);assert.doesNotMatch(module.ownSection({role:'Coordinateur',serviceAbbreviation:'B2B'}),/Enregistrer mon service/);assert.equal(module.ownSection({role:'Contrôleur'}),'');
 await db.close();console.log('PASS: existing technician migration, coordinator self-service, account creation rollback, office/service routing, cross-company denial, office-wide validation and immutable request origin.');
})().catch(error=>{console.error(error);process.exitCode=1;});
