const assert=require('node:assert/strict');
const actor=(role,uid=role)=>({uid,name:uid,role,is_active:true,company_id:'A',user_id:5,controlScopes:{MOOV:true}});
const tech=actor('Technicien'),coord=actor('Coordinateur'),manager=actor('Gestionnaire');
const source={key:'sortie:abc:0',op:'MOOV',label:'Câble 1FO',materialType:'CÂBLE',issuedQty:100,reference:'BON-ORIGINE'};
(async()=>{
const C=await import('../supabase/functions/cable-offcuts/core.ts');
let serial=0,state;
const execute=async(command,who=tech,id='c'+(++serial))=>{
  const context={op:'MOOV',company:'A',now:'2026-09-17T15:00:00Z',id,source};
  state=await C.transition(state,command,who,context);return id;
};
const ret=await execute({action:'return',qty:40.25,motif:'Fin du chantier'});
assert.equal(Object.keys(state.lots).length,0,'A declaration must not increase stock');
await assert.rejects(execute({action:'receiveReturn',target:ret},manager),/coordinateur/);
await assert.rejects(execute({action:'approveReturn',target:ret},tech),/coordinateur/);
await execute({action:'approveReturn',target:ret},coord);
assert.equal(Object.keys(state.lots).length,0,'Coordination alone must not increase stock');
const receive={action:'receiveReturn',target:ret};await execute(receive,manager,'receive');
const lot=state.returns[ret].lotId;
assert.equal(state.lots[lot].qty,40.25);
const before=structuredClone(state);await execute(receive,manager,'receive');assert.deepEqual(state,before,'Network retries are idempotent');
await assert.rejects(execute(receive,manager),/coordinateur/);
await assert.rejects(execute({action:'return',qty:60,motif:'Trop long'}),/dépasse/);
await assert.rejects(execute({action:'manualEntry',label:'Câble',qty:1,motif:'Stock initial'},tech),/gestionnaire/);
const manual=await execute({action:'manualEntry',label:'Câble 1FO',qty:10.5,motif:'Inventaire entrepôt'},manager);
assert.equal(state.lots[manual].qty,10.5);assert.equal(state.lots[lot].qty,40.25,'Lots are not merged');
const req=await execute({action:'request',lotId:lot,qty:30,motif:'Chantier B'});
await assert.rejects(execute({action:'issue',target:req},manager),/non disponible/);
await execute({action:'approveRequest',target:req},coord);
const competing=await execute({action:'request',lotId:lot,qty:20,motif:'Chantier C'});
await execute({action:'approveRequest',target:competing},coord);
await execute({action:'issue',target:req},manager,'issue');
assert.equal(state.lots[lot].qty,10.25);
await assert.rejects(execute({action:'issue',target:competing},manager),/insuffisante/);
await execute({action:'issue',target:req},manager,'issue');assert.equal(state.lots[lot].qty,10.25);
const again=await execute({action:'return',issueId:req,qty:5.5,motif:'Fin chantier B'});
await execute({action:'approveReturn',target:again},coord);await execute({action:'receiveReturn',target:again},manager);
assert.equal(state.lots[state.returns[again].lotId].parentLotId,lot,'Reuse preserves the original lot chain');
await assert.rejects(execute({action:'return',issueId:req,qty:1,motif:'Vol'},actor('Technicien','other')),/technicien/);
for(const who of [actor('Contrôleur'),actor('Superviseur'),{...manager,company_id:'B'},{...manager,is_active:false},{...manager,controlScopes:{'ITC-B01':true}}])
  await assert.rejects(execute({action:'manualEntry',label:'Câble',qty:1,motif:'Test'},who));
for(const qty of [0,-1,NaN,Infinity,1.001,'',1000001])
  await assert.rejects(execute({action:'manualEntry',label:'Câble',qty,motif:'Test'},manager),/Longueur invalide/);
const reject=await execute({action:'return',qty:2,motif:'Erreur'});await execute({action:'rejectReturn',target:reject,reason:'Mauvais métrage'},coord);
assert.equal(state.returns[reject].status,'REJECTED');
await assert.rejects(execute({action:'approveReturn',target:reject},coord),/déjà traité/);
const sortie={company_id:'A',technicienUid:tech.uid,op:'MOOV',id:'S1',items:[]};
assert.ok(C.sourceFromSortie(sortie,{label:'Câble',qty:10},tech,'key',0));
assert.equal(C.sourceFromSortie({...sortie,company_id:'B'},{label:'Câble',qty:10},tech,'key',0),null);
assert.equal(C.sourceFromSortie(sortie,{label:'PTO',type:'BOÎTIER',qty:10},tech,'key',0),null);
assert.equal(C.sourceFromSortie(sortie,{label:'Câble',qty:10},actor('Technicien','other'),'key',0),null);
const inOut=Object.values(state.events).reduce((sum,e)=>sum+e.delta,0);
assert.equal(inOut,Object.values(state.lots).reduce((sum,l)=>sum+l.qty,0),'Ledger reconciles with available lengths');
console.log('PASS: cable-only origin, tenant/scoped roles, both approval stages, fractional metres, lot lineage, duplicate commands, competing issues, rejection and stock ledger reconciliation.');
})().catch(e=>{console.error(e);process.exitCode=1});
