const fs=require('fs'),assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const uuid=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
(async()=>{
 const db=new PGlite();
 await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('test.uid',true),'')::uuid $$;GRANT USAGE ON SCHEMA auth TO authenticated;`);
 const migration=n=>fs.readFileSync('supabase/migrations/'+n,'utf8');
 await db.exec(migration('202609180002_app_backend.sql').split('DO $$')[0]);
 await db.exec('GRANT SELECT,INSERT,UPDATE,DELETE ON app_records,app_settings TO authenticated;GRANT SELECT ON app_profiles TO authenticated;');
 for(const n of ['202609180005_validator_workflow.sql','202609190004_unconditional_workflow.sql','202609190005_city_stocks.sql','202609230001_manager_stock_operations.sql','202609230001_manager_stock_operations.sql'])await db.exec(migration(n));
 for(const [id,role,company] of [[1,'Gestionnaire','A'],[2,'Technicien','A'],[3,'Gestionnaire','B'],[4,'Superviseur','A']]){
  await db.query('INSERT INTO auth.users VALUES($1,$2)',[uuid(id),id+'@test']);
  await db.query('INSERT INTO app_profiles(user_id,company_id,role,control_scopes,profile) VALUES($1,$2,$3,$4,$5)',[uuid(id),company,role,JSON.stringify({OCI:true,MTN:true}),JSON.stringify({id,name:'Person '+id})]);
 }
 const initial={company_id:'A',op:'OCI',label:'CABLE',qty:100,type:'FIBRE'};
 await db.query("INSERT INTO app_records VALUES('stock','source','A',$1,now())",[JSON.stringify(initial)]);
 const as=async id=>{await db.exec('RESET ROLE');await db.query("SELECT set_config('test.uid',$1,false)",[uuid(id)]);await db.exec('SET ROLE authenticated');};
 const call=async(overrides={})=>{
  const a={id:10,key:'source',expected:initial,label:'CABLE',qty:5,dest:'MTN',reason:'Rééquilibrage',signature:'Manager',service:'DEP',...overrides};
  return (await db.query('SELECT manager_stock_operation($1,$2,$3,$4,$5,$6,$7,$8,$9) result',[uuid(a.id),a.key,JSON.stringify(a.expected),a.label,a.qty,a.dest,a.reason,a.signature,a.service])).rows[0].result;
 };
 const stock=async()=> (await db.query("SELECT payload FROM app_records WHERE collection='stock' AND record_key='source'")).rows[0].payload;
 await as(2);await assert.rejects(call(),/gestionnaire/);
 await as(3);await assert.rejects(call(),/affectation/);
 await as(1);
 for(const args of [{dest:'MOOV'},{dest:'OCI'},{qty:101},{qty:0},{qty:-1},{qty:'NaN'},{signature:''},{service:null},{reason:''},{expected:{...initial,qty:99}}])await assert.rejects(call(args));
 assert.equal((await stock()).qty,100);
 // A failure while creating the bon must roll back both inventory changes.
 await db.exec('RESET ROLE');
 await db.exec("CREATE FUNCTION reject_test_bon() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.collection='sorties' THEN RAISE EXCEPTION 'test bon failure'; END IF; RETURN NEW; END $$;CREATE TRIGGER reject_test_bon BEFORE INSERT ON app_records FOR EACH ROW EXECUTE FUNCTION reject_test_bon();");
 await as(1);await assert.rejects(call(),/test bon failure/);assert.equal((await stock()).qty,100);
 assert.equal((await db.query("SELECT count(*)::int n FROM app_records WHERE collection='stock'")).rows[0].n,1);
 await db.exec('RESET ROLE;DROP TRIGGER reject_test_bon ON app_records;');await as(1);
 let result=await call();assert.equal(result.after.qty,95);assert.equal(result.destinationAfterQty,5);
 await call();assert.equal((await stock()).qty,95,'retry never debits twice');
 assert.equal((await db.query("SELECT count(*)::int n FROM app_records WHERE collection='sorties'")).rows[0].n,1);
 assert.equal((await db.query("SELECT count(*)::int n FROM app_records WHERE collection='stockMovements'")).rows[0].n,2);
 result=await call({id:11,expected:await stock(),qty:3});assert.equal(result.destinationBeforeQty,5);assert.equal(result.destinationAfterQty,8);
 result=await call({id:12,expected:await stock(),label:'CABLE RENOMME',qty:0,dest:null,signature:null,service:null});assert.equal(result.after.qty,0);assert.equal((await stock()).label,'CABLE RENOMME');
 await assert.rejects(call({id:13,expected:initial,dest:null,qty:8}),/Actualisez/);
 await assert.rejects(db.exec("UPDATE app_records SET payload=jsonb_set(payload,'{qty}','-1') WHERE collection='stock' AND record_key='source'"),/bon/);
 await as(4);assert.equal((await db.query("SELECT count(*)::int n FROM app_records WHERE collection='notifications'")).rows[0].n,3);
 await db.exec('RESET ROLE');
 const deletion=migration('202609240003_delete_manager_stock_item.sql');await db.exec(deletion);await db.exec(deletion);
 const snapshot=await stock();
 const remove=expected=>db.query('SELECT delete_manager_stock_item($1,$2,$3)',[uuid(20),'source',JSON.stringify(expected)]);
 await as(2);await assert.rejects(remove(snapshot),/gestionnaire/);
 await as(3);await assert.rejects(remove(snapshot),/affectation/);
 await as(1);await assert.rejects(remove(initial),/Actualisez/);
 await assert.rejects(db.exec("DELETE FROM app_records WHERE collection='stock' AND record_key='source'"),/Suppression interdite/);
 await db.exec('RESET ROLE');await db.exec("UPDATE app_profiles SET control_scopes='{}' WHERE user_id='"+uuid(1)+"'");
 await as(1);await assert.rejects(remove(snapshot),/affectation/);
 await db.exec('RESET ROLE');await db.exec("UPDATE app_profiles SET control_scopes='{\"OCI\":true}' WHERE user_id='"+uuid(1)+"'");
 await as(1);await remove(snapshot);await remove(snapshot);
 assert.equal((await db.query("SELECT count(*)::int n FROM app_records WHERE collection='stock' AND record_key='source'")).rows[0].n,0);
 const audit=(await db.query("SELECT payload FROM app_records WHERE collection='platformAuditLogs' AND record_key=$1",[uuid(20)])).rows[0].payload;
 assert.deepEqual(audit.before,snapshot);
 assert.equal((await db.query("SELECT count(*)::int n FROM app_records WHERE collection='sorties'")).rows[0].n,2,'past output history is preserved');
 await db.close();
 assert.ok(!fs.readFileSync('assets/supabase-store.js','utf8').includes('setInterval('),'no background refresh timer');
 console.log('PASS: manager corrections, transfer debit/credit/bon/audit, replay safety, stale writes, quantity validation, roles and tenant/stock isolation.');
})().catch(e=>{console.error(e);process.exitCode=1});
