const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const {PGlite}=require('@electric-sql/pglite');
const {stripTypeScriptTypes}=require('node:module');
(async()=>{
 const db=new PGlite();
 await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('test.uid',true),'')::uuid $$;`);
 await db.exec(fs.readFileSync('supabase/migrations/202609180002_app_backend.sql','utf8').split('DO $$')[0]);
 const migration=fs.readFileSync('supabase/migrations/202609240002_push_subscriptions.sql','utf8');await db.exec(migration);await db.exec(migration);
 const uid='00000000-0000-0000-0000-000000000007';
 await db.query('INSERT INTO auth.users VALUES($1)',[uid]);
 await db.query("INSERT INTO app_profiles(user_id,company_id,role,profile) VALUES($1,'A','Gestionnaire','{\"id\":7}')",[uid]);
 await db.query("SELECT set_config('test.uid',$1,false)",[uid]);await db.exec('SET ROLE authenticated');
 await assert.rejects(db.exec("SELECT register_app_push_token('short')"),/invalide/);
 await db.exec("SELECT register_app_push_token('device-token-long-enough');SELECT register_app_push_token('device-token-long-enough');");
 await assert.rejects(db.exec('SELECT * FROM app_push_tokens'),/permission/);
 await db.exec('RESET ROLE');assert.equal((await db.query('SELECT count(*)::int n FROM app_push_tokens')).rows[0].n,1);
 await db.exec('UPDATE app_profiles SET is_active=false;SET ROLE authenticated');await assert.rejects(db.exec("SELECT register_app_push_token('device-token-long-enough')"),/actif/);
 await db.close();
 // Exercise webhook routing and Web Push failures without real credentials/network.
 let handler,read=false,active=true,sendStatus=200,removed=false;
 const sent=[];
 const dbMock={from(table){let deleting=false;const query={select(){return this;},eq(){return this;},in(){return this;},delete(){deleting=true;return this;},maybeSingle(){return Promise.resolve({data:{company_id:'A',payload:{userId:7,lu:read,message:'Commande'}}});},then(resolve){if(deleting){removed=true;resolve({error:null});return;}resolve({data:table==='app_profiles'?(active?[{user_id:uid,profile:{id:'7'}}]:[]):[{endpoint:'https://push.example/subscription',user_id:uid,subscription:{endpoint:'https://push.example/subscription',keys:{p256dh:'public-key',auth:'auth-key'}}}]});}};return query;}};
 const webpush={setVapidDetails(subject,pub,priv){assert.equal(pub,'public');assert.equal(priv,'private');},async sendNotification(subscription,payload,options){sent.push({subscription,payload:JSON.parse(payload),options});if(sendStatus!==200)throw {statusCode:sendStatus};}};
 const context={Response,console,createClient:()=>dbMock,webpush,Deno:{env:{get:name=>({PUSH_WEBHOOK_SECRET:'secret',VAPID_PUBLIC_KEY:'public',VAPID_PRIVATE_KEY:'private',VAPID_SUBJECT:'mailto:test@example.com'}[name]||'test')},serve:fn=>handler=fn}};
 vm.createContext(context);
 const source=fs.readFileSync('supabase/functions/notification-push/index.ts','utf8').replace(/^import .*;\r?\n/gm,'');
 vm.runInContext(stripTypeScriptTypes(source),context);
 const call=(secret='secret',collection='notifications')=>handler(new Request('https://example.test',{method:'POST',headers:{'x-push-secret':secret},body:JSON.stringify({type:'INSERT',table:'app_records',record:{record_key:'n1',collection}})}));
 assert.equal((await call('wrong')).status,401);await call('secret','stock');assert.equal(sent.length,0);
 read=true;await call();assert.equal(sent.length,0);read=false;active=false;await call();assert.equal(sent.length,0);active=true;
 assert.equal((await call()).status,200);assert.equal(sent[0].payload.body,'Commande');assert.equal(sent[0].options.urgency,'high');
 sendStatus=503;assert.equal((await call()).status,502);assert.equal(removed,false);
 sendStatus=404;assert.equal((await call()).status,200);assert.equal(removed,true);
 let unsubscribed=false,deleted=0,registered=0,currentUid=uid;
 const status={};
 const subscription={endpoint:'https://push.example/subscription',toJSON:()=>({endpoint:'https://push.example/subscription',keys:{p256dh:'public-key',auth:'auth-key'}}),unsubscribe:async()=>{unsubscribed=true;return true;}};
 const registration={pushManager:{getSubscription:async()=>subscription,subscribe:async()=>subscription}};
 const calls=[];const browser={console,atob:globalThis.atob,PushManager:function(){},document:{getElementById:()=>status},navigator:{serviceWorker:{ready:Promise.resolve(registration)}},Notification:{permission:'granted',requestPermission:async()=> 'granted'},ITCPushConfig:{vapidPublicKey:'AQ'},ITCSupabaseConfig:{client:{auth:{getUser:async()=>({data:{user:{id:currentUid}}})},rpc:async(name,args)=>{calls.push({name,args});if(name==='register_app_push_subscription')registered++;if(name==='remove_app_push_subscription')deleted++;return {};}}}};
 browser.window=browser;vm.createContext(browser);vm.runInContext(fs.readFileSync('assets/push-notifications.js','utf8'),browser);
 const button={};await browser.enablePushNotifications(button);assert.equal(registered,1);assert.equal(button.disabled,false);
 assert.equal(calls[0].args.push_subscription.endpoint,subscription.endpoint);
 await browser.disablePushNotifications();assert.equal(deleted,1);assert.equal(unsubscribed,true);
 console.log('PASS: Web Push subscription permissions, webhook authentication, recipient filtering, delivery failures and device unsubscribe.');
})().catch(error=>{console.error(error);process.exitCode=1});
