const fs=require('fs'),assert=require('node:assert/strict'),vm=require('vm'),{PGlite}=require('@electric-sql/pglite');
const uuid=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
(async()=>{
 const db=new PGlite();
 await db.exec(`CREATE ROLE authenticated;CREATE ROLE anon;CREATE ROLE service_role;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('test.uid',true),'')::uuid $$;GRANT USAGE ON SCHEMA auth TO authenticated;`);
 const migration=n=>fs.readFileSync('supabase/migrations/'+n,'utf8');
 await db.exec(migration('202609180002_app_backend.sql').split('DO $$')[0]);
 await db.exec('GRANT SELECT,INSERT,UPDATE,DELETE ON app_records,app_settings TO authenticated;GRANT SELECT ON app_profiles TO authenticated;');
 for(const file of ['202609180005_validator_workflow.sql','202609190004_unconditional_workflow.sql','202609190005_city_stocks.sql','202609240004_bureau02_substocks.sql','202609240004_bureau02_substocks.sql'])await db.exec(migration(file));
 for(const [id,role,company,scopes] of [[1,'Gestionnaire','A',{'ITC-B02':true,MOOV:true}],[2,'Gestionnaire','A',{'ITC-B01':true}],[3,'Gestionnaire','B',{'ITC-B02':true}],[4,'Technicien','A',{'ITC-B02':true}]]){
  await db.query('INSERT INTO auth.users(id) VALUES($1)',[uuid(id)]);
  await db.query('INSERT INTO app_profiles(user_id,company_id,role,control_scopes,profile) VALUES($1,$2,$3,$4,$5)',[uuid(id),company,role,JSON.stringify(scopes),JSON.stringify({id,name:'Person '+id})]);
 }
 const initial={company_id:'A',op:'ITC-B02',label:'BOX',qty:100,type:'BOX'};
 await db.query("INSERT INTO app_records(collection,record_key,company_id,payload) VALUES('stock','box','A',$1)",[initial]);
 const as=async id=>{await db.exec('RESET ROLE');await db.query("SELECT set_config('test.uid',$1,false)",[uuid(id)]);await db.exec('SET ROLE authenticated');};
 const stock=async()=> (await db.query("SELECT payload FROM app_records WHERE collection='stock' AND record_key='box'")).rows[0].payload;
 const reorg=(expected,buckets)=>db.query('SELECT reorganize_stock_substocks($1,$2,$3)',['box',expected,buckets]);
 for(const id of [2,3,4]){await as(id);await assert.rejects(reorg(initial,{production:40}),/serv/);}
 await as(1);
 for(const b of [{production:101},{production:-1},{unknown:1},{production:'1'},null])await assert.rejects(reorg(initial,b));
 await reorg(initial,{production:40,deploiement:30,maintenance:20});assert.equal((await stock()).qty,100);
 await assert.rejects(reorg(initial,{production:40}),/modifi/);
 const receive=()=>db.query('SELECT receive_stock_substock($1,$2,$3,$4,$5,$6)',[uuid(10),'ITC-B02','BOX','BOX',5,'deploiement']);
 await receive();await receive();let s=await stock();assert.equal(s.qty,105);assert.equal(s.subStocks.deploiement,35);
 assert.equal((await db.query("SELECT count(*)::int n FROM app_records WHERE collection='stockMovements'")).rows[0].n,1);
 await assert.rejects(db.exec("UPDATE app_records SET payload=jsonb_set(payload,'{subStocks}','{}') WHERE collection='stock' AND record_key='box'"),/organisation/);
 await db.exec('RESET ROLE');
 const request={id:'request',company_id:'A',op:'ITC-B02',status:'EN ATTENTE GESTIONNAIRE',assignedGestionnaireUid:uuid(1),validatorDecision:{approved:true},items:[{label:'BOX',qty:45}]};
 await db.query("INSERT INTO app_records(collection,record_key,company_id,payload) VALUES('demandes','request','A',$1)",[request]);
 await as(1);await db.exec("SELECT issue_validated_request('request','Manager','DEP')");
 s=await stock();assert.equal(s.qty,60);assert.deepEqual(s.subStocks,{production:0,deploiement:30,maintenance:20});
 await db.exec("SELECT issue_validated_request('request','Manager','DEP')");assert.equal((await stock()).qty,60,'issue retry does not debit again');
 await db.query('SELECT manager_stock_operation($1,$2,$3,$4,$5,$6,$7,$8,$9)',[uuid(20),'box',s,'BOX',10,'MOOV','Transfer','Manager','DEP']);
 s=await stock();assert.equal(s.qty,50);assert.equal(s.subStocks.deploiement,20);
 const target=(await db.query("SELECT payload FROM app_records WHERE collection='stock' AND payload->>'op'='MOOV'")).rows[0].payload;
 assert.equal(target.qty,10);assert.equal(target.subStocks,undefined,'transfer never copies source allocation into destination');
 await db.exec('RESET ROLE');
 const explicit=migration('202609240005_explicit_substock_issues.sql');await db.exec(explicit);await db.exec(explicit);
 await db.query("INSERT INTO app_records(collection,record_key,company_id,payload) VALUES('demandes','chosen','A',$1)",[{...request,id:'chosen',items:[{op:'ITC-B02',label:'BOX',qty:8}]}]);
 await as(1);
 const choose=items=>db.query("SELECT issue_validated_request_substocks('chosen','Manager','DEP',$1)",[items]);
 await assert.rejects(db.exec("SELECT issue_validated_request('chosen','Manager','DEP')"),/sous-stock/);
 await assert.rejects(choose([{op:'ITC-B02',label:'BOX',qty:9,substock:'maintenance'}]),/exactement/);
 await assert.rejects(choose([{op:'ITC-B02',label:'BOX',qty:8,substock:'production'}]),/insuffisante/);
 assert.equal((await stock()).qty,50);
 const selection=[{op:'ITC-B02',label:'BOX',qty:5,substock:'maintenance'},{op:'ITC-B02',label:'BOX',qty:3,substock:'unallocated'}];
 await choose(selection);await choose(selection);s=await stock();assert.equal(s.qty,42);assert.deepEqual(s.subStocks,{production:0,deploiement:20,maintenance:15});assert.equal(s._substockDebit,undefined);
 const issued=(await db.query("SELECT payload FROM app_records WHERE collection='sorties' AND payload->>'sourceDemandeId'='chosen'")).rows[0].payload;assert.deepEqual(issued.items,selection);
 await db.exec('RESET ROLE');await db.exec("UPDATE app_profiles SET is_active=false WHERE user_id='"+uuid(1)+"'");await as(1);await assert.rejects(receive());
 await db.close();
 const context={window:{ControlCore:require('../assets/control-core')}};vm.createContext(context);vm.runInContext(fs.readFileSync('assets/stock-substocks.js','utf8'),context);
 const mod=context.window.StockSubstocks;mod.setup({profile:()=>({role:'Gestionnaire',company_id:'A',controlScopes:{'ITC-B02':true,MOOV:true}}),data:()=>({stock:[s,{...s,op:'MOOV',company_id:'B'}]})});
 assert.equal(mod.owns('MOOV'),true);assert.equal(mod.owns('ITC-BOUAKE'),false);assert.equal(mod.quantities(initial).unallocated,100);assert.equal(mod.quantities(s).unallocated,7);
 assert.equal(mod.pickerRows(['ITC-B02']).length,3);assert.equal(mod.pickerRows(['MOOV']).length,0);
 const picker=mod.pickerHtml(['ITC-B02'],[{op:'ITC-B02',label:'BOX',substock:'maintenance',qty:2}]);assert.match(picker,/data-substock="maintenance"/);assert.match(picker,/max="15" value="2"/);assert.match(picker,/Stock-production/);
 assert.match(mod.receptionField(),/r-substock/);
 mod.setup({profile:()=>({role:'Gestionnaire',controlScopes:{'ITC-B01':true}})});assert.equal(mod.enabled(),false);assert.equal(mod.receptionField(),'');
 console.log('PASS: B02 substock scope, existing quantity preservation, invalid/stale distribution, receipt replay, automatic issue priority, transfer isolation and inactive accounts.');
})().catch(error=>{console.error(error);process.exitCode=1;});
